### POST request to register user
POST http://localhost:8081/api/v1/user
Content-Type: application/json

{
  "email": "test@example.com",
  "password": "password123"
}

### Login
POST http://localhost:8081/api/v1/auth/login
Content-Type: application/json

{
  "email": "test@example.com",
  "password": "password123"
}

> {%
    client.global.set(
        "token",
        response.headers.valueOf("Authorization")
    );
%}

### Profile
GET http://localhost:8081/api/v1/user
Authorization: {{token}}


### Get all task
GET http://localhost:8081/api/v1/tasks
Authorization: {{token}}

### Create incorrect task
POST http://localhost:8081/api/v1/tasks
Authorization: {{token}}
Content-Type: application/json

{
  "name": "moreThanOneHundredCharactersMoreThanOneHundredCharactersMoreThanOneHundredCharactersMoreThanOneHundredCharacters",
  "description": "",
  "isDone": true
}

### Create task
POST http://localhost:8081/api/v1/tasks
Authorization: {{token}}
Content-Type: application/json

{
  "name": "Buy groceries",
  "description": "Cucumber, lettuce, corn",
  "isDone": false
}

> {%
    client.global.set("taskId", response.body.id);
%}

### Update not exist task
PUT http://localhost:8081/api/v1/tasks/1000000000
Authorization: {{token}}
Content-Type: application/json

{
  "name": "Updated Buy groceries",
  "description": "Cucumber, lettuce, corn, water",
  "isDone": true
}


### Updated task
PUT http://localhost:8081/api/v1/tasks/{{taskId}}
Authorization: {{token}}
Content-Type: application/json

{
  "name": "Updated Buy groceries",
  "description": "Cucumber, lettuce, corn, water",
  "isDone": true
}

### Delete one task
DELETE http://localhost:8081/api/v1/tasks/{{taskId}}
Authorization: {{token}}
