services:
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tm_db
    ports:
      - "5432:5432"
  kafka:
    image: apache/kafka:4.1.0
    ports:
      - "9092:9092"
