services:
  mysql:
    container_name: mysql-container
    image: mysql:8
    volumes:
      - mysql_volume:/var/lib/mysql
    environment:
      MYSQL_DATABASE: task_manager
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
volumes:
  mysql_volume: