app:
  jwt:
    secret:  ${JWT_SECRET}
    access-token-expiration: 15m
server:
  port: 8080
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://db:5432/tm_db
    username: user
    password: password
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: classpath:liquibase/changelog.yml
springdoc:
  override-with-generic-response: false